-- MySQL Script generated by MySQL Workbench
-- Fri 07 Jul 2017 04:03:24 AM EDT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema HotelReservations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema HotelReservations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `HotelReservations` DEFAULT CHARACTER SET latin1 ;
USE `HotelReservations` ;

-- -----------------------------------------------------
-- Table `HotelReservations`.`Amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Amenities` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Amenities` (
  `AmenityId` INT(11) NOT NULL AUTO_INCREMENT,
  `AmenityType` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`AmenityId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `HotelReservations`.`Customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Customers` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Customers` (
  `CustomerId` INT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Phone` CHAR NOT NULL,
  PRIMARY KEY (`CustomerId`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE UNIQUE INDEX `customerId_UNIQUE` ON `HotelReservations`.`Customers` (`CustomerId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`Hotels`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Hotels` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Hotels` (
  `HotelId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `State` VARCHAR(45) NOT NULL,
  `City` VARCHAR(45) NOT NULL,
  `StreetAddress` VARCHAR(45) NOT NULL,
  `ZipCode` CHAR NOT NULL,
  PRIMARY KEY (`HotelId`));


-- -----------------------------------------------------
-- Table `HotelReservations`.`RoomTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`RoomTypes` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`RoomTypes` (
  `RoomTypeId` INT NOT NULL AUTO_INCREMENT,
  `RoomType` CHAR NOT NULL,
  `MaxOccupants` INT NOT NULL,
  `BaseCost` DECIMAL(6,2) NOT NULL,
  PRIMARY KEY (`RoomTypeId`));


-- -----------------------------------------------------
-- Table `HotelReservations`.`Rooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Rooms` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Rooms` (
  `RoomId` INT NOT NULL,
  `HotelId` INT(11) NOT NULL,
  `Floor` INT(11) NOT NULL,
  `RoomNumber` INT(11) NOT NULL,
  `RoomTypeId` INT(11) NOT NULL,
  PRIMARY KEY (`RoomId`),
  CONSTRAINT `fk_HotelId`
    FOREIGN KEY (`HotelId`)
    REFERENCES `HotelReservations`.`Hotels` (`HotelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_RoomTypeId`
    FOREIGN KEY (`RoomTypeId`)
    REFERENCES `HotelReservations`.`RoomTypes` (`RoomTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_HotelId_idx` ON `HotelReservations`.`Rooms` (`HotelId` ASC);

CREATE INDEX `fk_RoomTypeId_idx` ON `HotelReservations`.`Rooms` (`RoomTypeId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`Room_has_Amenities`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Room_has_Amenities` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Room_has_Amenities` (
  `RoomId` INT(11) NOT NULL,
  `AmenityId` INT(11) NOT NULL,
  `AmenityCount` INT NULL,
  PRIMARY KEY (`RoomId`, `AmenityId`),
  CONSTRAINT `fk_RoomId`
    FOREIGN KEY (`RoomId`)
    REFERENCES `HotelReservations`.`Rooms` (`HotelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_AmenityId`
    FOREIGN KEY (`AmenityId`)
    REFERENCES `HotelReservations`.`Amenities` (`AmenityId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_AmenityId` ON `HotelReservations`.`Room_has_Amenities` (`AmenityId` ASC);

CREATE INDEX `fk_RoomId` ON `HotelReservations`.`Room_has_Amenities` (`RoomId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`DeltaTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`DeltaTypes` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`DeltaTypes` (
  `DeltaTypeId` INT NOT NULL,
  `DeltaType` VARCHAR(1) NOT NULL,
  PRIMARY KEY (`DeltaTypeId`));


-- -----------------------------------------------------
-- Table `HotelReservations`.`Promotions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Promotions` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Promotions` (
  `PromotionCode` VARCHAR(25) NOT NULL,
  `Amount` DECIMAL(6,2) NOT NULL,
  `DeltaTypeId` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  PRIMARY KEY (`PromotionCode`),
  CONSTRAINT `fk_DeltaTypeId`
    FOREIGN KEY (`DeltaTypeId`)
    REFERENCES `HotelReservations`.`DeltaTypes` (`DeltaTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_DeltaTypeId_idx` ON `HotelReservations`.`Promotions` (`DeltaTypeId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`Reservations`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Reservations` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Reservations` (
  `ReservationId` INT NOT NULL AUTO_INCREMENT,
  `HotelId` INT NOT NULL,
  `CustomerId` INT NOT NULL,
  `StartDate` DATE NOT NULL,
  `EndDate` DATE NOT NULL,
  `PromotionCode` VARCHAR(25) NULL,
  `InvoiceTotal` DECIMAL(7,2) NULL,
  `PaymentReceived` DECIMAL(7,2) NULL,
  `AmountDue` DECIMAL(7,2) NULL,
  PRIMARY KEY (`ReservationId`),
  CONSTRAINT `fk_ResHotelId`
    FOREIGN KEY (`HotelId`)
    REFERENCES `HotelReservations`.`Hotels` (`HotelId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CustomerId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `HotelReservations`.`Customers` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PromotionCode`
    FOREIGN KEY (`PromotionCode`)
    REFERENCES `HotelReservations`.`Promotions` (`PromotionCode`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_HotelId_idx` ON `HotelReservations`.`Reservations` (`HotelId` ASC);

CREATE INDEX `fk_CustomerId_idx` ON `HotelReservations`.`Reservations` (`CustomerId` ASC);

CREATE INDEX `fk_PromotionCode_idx` ON `HotelReservations`.`Reservations` (`PromotionCode` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`Guests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Guests` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Guests` (
  `GuestId` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(35) NOT NULL DEFAULT 'Minor',
  `Age` INT NULL,
  PRIMARY KEY (`GuestId`));


-- -----------------------------------------------------
-- Table `HotelReservations`.`ReservationsGuests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`ReservationsGuests` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`ReservationsGuests` (
  `ReservationId` INT NOT NULL,
  `GuestId` INT NOT NULL,
  PRIMARY KEY (`ReservationId`, `GuestId`),
  CONSTRAINT `fk_ReservationId`
    FOREIGN KEY (`ReservationId`)
    REFERENCES `HotelReservations`.`Reservations` (`ReservationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GuestId`
    FOREIGN KEY (`GuestId`)
    REFERENCES `HotelReservations`.`Guests` (`GuestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_GuestId` ON `HotelReservations`.`ReservationsGuests` (`GuestId` ASC);

CREATE INDEX `fk_ReservationId` ON `HotelReservations`.`ReservationsGuests` (`ReservationId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`ReservationsRooms`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`ReservationsRooms` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`ReservationsRooms` (
  `ReservationRoomId` INT NOT NULL,
  `ReservationId` INT NOT NULL,
  `RoomId` INT NOT NULL,
  PRIMARY KEY (`ReservationRoomId`),
  CONSTRAINT `fk_ReservationsId`
    FOREIGN KEY (`ReservationId`)
    REFERENCES `HotelReservations`.`Reservations` (`ReservationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ResRoomId`
    FOREIGN KEY (`RoomId`)
    REFERENCES `HotelReservations`.`Rooms` (`RoomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fl_RoomId_idx` ON `HotelReservations`.`ReservationsRooms` (`RoomId` ASC);

CREATE INDEX `fk_ReservationId_idx` ON `HotelReservations`.`ReservationsRooms` (`ReservationId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`CustomersGuests`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`CustomersGuests` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`CustomersGuests` (
  `CustomerId` INT(11) NOT NULL,
  `GuestId` INT NOT NULL,
  PRIMARY KEY (`CustomerId`, `GuestId`),
  CONSTRAINT `fk_CustomersId`
    FOREIGN KEY (`CustomerId`)
    REFERENCES `HotelReservations`.`Customers` (`CustomerId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_GuestsId`
    FOREIGN KEY (`GuestId`)
    REFERENCES `HotelReservations`.`Guests` (`GuestId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

CREATE INDEX `fk_CustomerId` ON `HotelReservations`.`CustomersGuests` (`CustomerId` ASC);

CREATE INDEX `fk_GuestId` ON `HotelReservations`.`CustomersGuests` (`GuestId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`BillDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`BillDetails` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`BillDetails` (
  `BillDetailsId` INT NOT NULL,
  `ReservationId` INT NOT NULL,
  `ReservationRoomId` INT NOT NULL,
  `Date` DATE NOT NULL,
  `RoomCharge` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`BillDetailsId`),
  CONSTRAINT `fk_ReservationIds`
    FOREIGN KEY (`ReservationId`)
    REFERENCES `HotelReservations`.`Reservations` (`ReservationId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ReservationRoomsId`
    FOREIGN KEY (`ReservationRoomId`)
    REFERENCES `HotelReservations`.`ReservationsRooms` (`ReservationRoomId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'Constraint ReservationRoomDate UNIQUE (Date, ReservationRoomId)';

CREATE INDEX `fk_ReservationId_idx` ON `HotelReservations`.`BillDetails` (`ReservationId` ASC);

CREATE INDEX `fk_ReservationRoomId_idx` ON `HotelReservations`.`BillDetails` (`ReservationRoomId` ASC);


-- -----------------------------------------------------
-- Table `HotelReservations`.`ConvenienceTypes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`ConvenienceTypes` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`ConvenienceTypes` (
  `ConvenienceTypeId` INT NOT NULL,
  `ConvenienceType` VARCHAR(25) NOT NULL,
  `ConvenienceTypeCost` DECIMAL(7,2) NOT NULL,
  PRIMARY KEY (`ConvenienceTypeId`));


-- -----------------------------------------------------
-- Table `HotelReservations`.`Conveniences`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `HotelReservations`.`Conveniences` ;

CREATE TABLE IF NOT EXISTS `HotelReservations`.`Conveniences` (
  `BillDetailsId` INT NOT NULL,
  `ConvenienceType` INT NOT NULL,
  `ConvenienceCost` DECIMAL(7,2) NULL,
  PRIMARY KEY (`BillDetailsId`),
  CONSTRAINT `fk_BillDetailsId`
    FOREIGN KEY (`BillDetailsId`)
    REFERENCES `HotelReservations`.`BillDetails` (`BillDetailsId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ConvenienceTypeId`
    FOREIGN KEY (`ConvenienceType`)
    REFERENCES `HotelReservations`.`ConvenienceTypes` (`ConvenienceTypeId`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION);

CREATE INDEX `fk_ConvenienceTypeId_idx` ON `HotelReservations`.`Conveniences` (`ConvenienceType` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
